// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from  "dotenv";
import { defineConfig } from "prisma/config";
dotenv.config();
export default defineConfig({
  schema: "./src/prisma/schema.prisma",
  migrations: {
    path: "./src/prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
