touch \
src/app.ts \
src/server.ts \
src/config/env.ts \
src/config/prisma.ts \
src/controllers/auth.controller.ts \
src/controllers/health.controller.ts \
src/middlewares/auth.middleware.ts \
src/middlewares/error.middleware.ts \
src/routes/auth.routes.ts \
src/routes/index.ts \
src/types/express.d.ts \
src/utils/jwt.ts \
src/utils/password.ts \
src/utils/logger.ts \
tests/health.test.ts \
prisma/schema.prisma \
.env \
.env.example \
nodemon.json \
.eslintrc.cjs \
.prettierrc \
.eslintignore \
.gitignore \
tsconfig.json \
tsconfig.build.json \
jest.config.ts \
README.md